apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-deploy
  namespace: aws0418
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      imagePullSecrets:
        - name: page-pull-secret
      containers:
        - name: main
          image: hub.aws9.pri/page/main:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: main-svc
  namespace: aws0418
spec:
  type: ClusterIP
  selector:
    app: main
  ports:
    - port: 80
      targetPort: 80
