{{- range .Values.apps }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}-deploy
  labels:
    app: {{ .name }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      imagePullSecrets:
        - name: page-pull-secret
      containers:
        - name: {{ .name }}
          image: {{ $.Values.image.repository }}/{{ .name }}:{{ $.Values.image.tag }}
          ports:
            - containerPort: 80
          resources: {{ toYaml $.Values.resources | nindent 12 }}
---
{{- end }}