apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: page-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: www.aws9.pri
      http:
        paths:
        {{- range .Values.apps }}
        - path: "/{{ .name }}(/|$)"
          pathType: Prefix
          backend:
            service:
              name: {{ .name }}-svc
              port:
                number: {{ $.Values.service.port }}
        {{- end }}
